var p = "static/";

var tasks = [
    p + "js/jquery.min.js",
    p + "js/resize.js",
    p + "img/bg.png",
    p + "img/branch-left.png",
    p + "img/branchRight-kv.png",
    p + "img/bridge-p2.png",
    p + "img/bridge-p3.png",
    p + "img/bus-p2.png",
    p + "img/car-p2.png",
    p + "img/car-p3.png",
    p + "img/dial-p3.png",
    p + "img/dust-kv.png",
    p + "img/dust-p2.png",
    p + "img/dust-p3.png",
    p + "img/dust-p4.png",
    p + "img/fireworks.png",
    p + "img/floor-p4.png",
    p + "img/gearBottom-kv.png",
    p + "img/gearBottom-p2.png",
    p + "img/gearMiddle-kv.png",
    p + "img/gearMiddle-p2.png",
    p + "img/gearTop-kv.png",
    p + "img/gearTop-p2.png",
    p + "img/goddess-p3.png",
    p + "img/house-kv.png",
    p + "img/landmark-kv.png",
    p + "img/logo.png",
	p + "img/up.png",
    p + "img/panda.png",
    p + "img/prospect-kv.png",
    p + "img/santa-kv.png",
    p + "img/santa.png",
    p + "img/slogan.png",
    p + "img/start-kv.png",
    p + "img/start-p2.png",
    p + "img/title-end.png",
    p + "img/title-kv.png",
    p + "img/title-p2.png",
    p + "img/title-p3.png",
    p + "img/title-p4.png",
    p + "img/tower-p2.png",
    p + "img/trees-kv.png",
    p + "img/trees-p2.png",
    p + "img/trees-p3.png",
    p + "img/wheel-p2.png",
    p + "img/windmill-p3.png",
    p + "css/style.css"
];

$('#J_progress').html("0/" + tasks);
